# Generated by Django 5.2.1 on 2025-12-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requesters", "0002_alter_request_created_at"),
        ("users", "0002_alter_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="completed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requesters.request",
                    ),
                ),
            ],
        ),
    ]
